#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"
set +e;

case "$1" in
  airbrake-deploy)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    verify_app_name "$2"
    APP="$2"
    [[ -z $(dokku config:get "$APP" AIRBRAKE_API_KEY) ]] && echo "AIRBRAKE_API_KEY is not defined for $APP" && exit 1
    echo "Airbrake deploy hook is enabled for $APP"
    ;;

  help)
    cat && cat<<EOF
    airbrake-deploy <app>                           Display the current airbrake deploy hook status of app
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
