#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; REV="$2"
APP_ROOT="$DOKKU_ROOT/$APP"

if [[ ! -d "$APP_ROOT" ]]; then
  mkdir -p "$APP_ROOT"
fi

echo "$REV" > "$APP_ROOT/.dokku-git-rev"
